# Generated by Django 3.1 on 2020-08-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roast_boast',
            name='boast',
            field=models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')]),
        ),
    ]
